server:
  port: 9001
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/secret_data?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: liuzhirui
    password: l180413L.
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: service-provider
  redis:
    port: 6379
    host: 127.0.0.1
mybatis:
  type-aliases-package: com.echo.service.pojo
  mapper-locations: classpath:mybatis/mappers/**/*.xml
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:10086/eureka
#    register-with-eureka: true
#  instance:
#    lease-renewal-interval-in-seconds: 5
#    lease-expiration-duration-in-seconds: 15