server:
  port: 9091
spring:
  application:
    name: service-consumer
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
    fetch-registry: true
    registry-fetch-interval-seconds: 5
feign:
  hystrix:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 40000
        readTimeout: 40000
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false
        isolation:
          thread:
            timeoutInMilliseconds: 40000
